### ISSUE TITLE
AWS Group Icons

### ISSUE THREAD

**Issue by leoharis** [JustDerb/yed-aws-palettes#2]
Hi,

Is there a file for Group Icons for the AWS diagrams as .graphml files?

Thanks

**Comment by JustDerb** [comment]
For "Group Icons" are you talking about the grouping boxes that come from the PowerPoint asset? These are things like AWS account, Region, VPC subnet, etc:

<img width="933" alt="Screen Shot 2022-08-31 at 8 25 52 AM" src="https://user-images.githubusercontent.com/1020220/187717174-a40d53ef-fd88-467c-9d53-c61d2f0df265.png">

If so, the Asset package does not have any SVG-related files for these. You currently will have to use the yED groups feature and then change the presentation properties for each group to closely match that of the ones above.

**Comment by leoharis** [comment]
Thanks for confirming as I couldn't find them.
