### ISSUE TITLE
AWS - SDK stencils are not loading

### ISSUE THREAD

**Issue by JADurham909** [JustDerb/yed-aws-palettes#2]
![2019-03-08_9-33-48](https://user-images.githubusercontent.com/574966/54034684-8b000180-4185-11e9-9d6b-d448a566dc8c.png)

Version 3.18.2
Master

**Comment by JustDerb** [comment]
Trying to import them manually (with using the script):

```
The attribute "r" of the element <circle> is required
```

Looks like the SVGs that were created for the Simple Icons were not in the correct format that yED expects...
