### ISSUE TITLE
add resource icons

### ISSUE THREAD

**Issue by ChipNowacek** [JustDerb/yed-aws-palettes#6]
Thank you for doing all this. It's so helpful. 

Any chance you could add the resource icons? I see them on [screenshot](https://github.com/JustDerb/yed-aws-palettes/blob/master/screenshot.png) but not in the palettes: 
![image](https://github.com/JustDerb/yed-aws-palettes/assets/3668197/12cb926b-cc76-444c-ad42-5de860a0adb7). 
If you tried and ran into trouble, could you tell me which commit you think came the closest and I'll try from there?

Thanks again.

**Comment by ChipNowacek** [comment]
Did the resources get lost because AWS reshuffled the packaging and split it out of architecture?

**Comment by JustDerb** [comment]
Hmm... it might have been. They love changing the packaging of their files for this, so it's alway chasing a moving target. If you find the root cause feel free to add it here. The https://github.com/JustDerb/yed-aws-palettes/blob/master/update.sh script will simply need to be updated to pull and place the files in the correct directories.

I won't have a ton of time in the coming weeks to root cause what's going on, so your alternative is to manually download the files and manually import them into the Palettes for now. Sizing might be different as an fyi.

**Comment by ChipNowacek** [comment]
The challenge is two-fold: _size_ and _folder structure_. 

### Size
You are currently grabbing the "32-pixel" svg files. That happens on line [110](https://github.com/JustDerb/yed-aws-palettes/blob/debdbda8087ac466ef0635f1679950afec61747f/update.sh#L110). That is indeed the best "size" for yEd palettes. Unfortunately, as of today (2023-09-15), AWS is only shipping "48-pixel" svg icons for resources. We'd need to use `ImageMagick` or something similar to resize the resource icons.

### Folder structure
Here's the current structure. 
![image](https://github.com/JustDerb/yed-aws-palettes/assets/3668197/1cb97cdb-7dad-4276-a5db-95ad0c48a39b)

The folder decision is made on line [39](https://github.com/JustDerb/yed-aws-palettes/blob/debdbda8087ac466ef0635f1679950afec61747f/update.sh#L39). We better put the resource icons in the architecture palettes. yEd doesn't handle lots of palettes very well. When there are too many, the scrolling on the palette window gets janky.

I will hack at it if I get a chance.

Again, thanks.

**Comment by JustDerb** [comment]
Hey, see if https://github.com/JustDerb/yed-aws-palettes/commit/5879378e667193b88ce6b869c3b9584853c41c9f solves the issue for you.

> AWS is only shipping "48-pixel" svg icons for resources

The translator actually should resize the SVGs so they are all the same size. I confirmed in the latest yEd software that they all can be dragged into the editor and appear to be the same size.

**Comment by ChipNowacek** [comment]
Thanks so much. I'll try shortly.
